### ISSUE TITLE
Missing intention documentation causes assertion failure to be logged in AppCode 2017.1 and IDE internal error balloon to show in 2017.2 EAP

### ISSUE THREAD

**Issue by codebrewer** [seanhenry/MockGenerator#2]
If I browse _Preferences -> Editor -> Intentions_ in AppCode 2017.1 then the following is logged to `idea.log`:
```
2017-06-26 22:41:23,864 [  12756]  ERROR - config.IntentionActionMetaData - Assertion failed: Intention Description Dir URL is null: Generate mock; MockGenerator, PluginClassLoader[codes.seanhenry.mockgenerator, 2] 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getDirURL(IntentionActionMetaData.java:109)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:151)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.a(IntentionManagerSettings.java:164)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaData(IntentionManagerSettings.java:155)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerIntentionMetaData(IntentionManagerSettings.java:86)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.b(IntentionManagerImpl.java:92)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-06-26 22:41:23,867 [  12759]  ERROR - config.IntentionActionMetaData - AppCode 2017.1.3  Build #OC-171.4694.27 
2017-06-26 22:41:23,867 [  12759]  ERROR - config.IntentionActionMetaData - JDK: 1.8.0_112-release 
2017-06-26 22:41:23,867 [  12759]  ERROR - config.IntentionActionMetaData - VM: OpenJDK 64-Bit Server VM 
2017-06-26 22:41:23,867 [  12759]  ERROR - config.IntentionActionMetaData - Vendor: JetBrains s.r.o 
2017-06-26 22:41:23,867 [  12759]  ERROR - config.IntentionActionMetaData - OS: Mac OS X 
2017-06-26 22:41:23,867 [  12759]  ERROR - config.IntentionActionMetaData - Last Action:  
2017-06-26 22:41:23,868 [  12760]  ERROR - til.concurrency.QueueProcessor - @NotNull method com/intellij/codeInsight/intention/impl/config/IntentionActionMetaData.getDirURL must not return null 
java.lang.IllegalStateException: @NotNull method com/intellij/codeInsight/intention/impl/config/IntentionActionMetaData.getDirURL must not return null
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getDirURL(IntentionActionMetaData.java:111)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:151)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.a(IntentionManagerSettings.java:164)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaData(IntentionManagerSettings.java:155)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerIntentionMetaData(IntentionManagerSettings.java:86)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.b(IntentionManagerImpl.java:92)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

An error is logged in AppCode 2017.2 EAP in the same circumstances and also at 'random' times when simply editing:
```
2017-06-26 21:13:28,658 [  34581]  ERROR - til.concurrency.QueueProcessor - Intention Description Dir URL is null: Generate mock; MockGenerator [Plugin: codes.seanhenry.mockgenerator] 
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Generate mock; MockGenerator [Plugin: codes.seanhenry.mockgenerator]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getDirURL(IntentionActionMetaData.java:114)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:151)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.a(IntentionManagerSettings.java:156)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaData(IntentionManagerSettings.java:147)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerIntentionMetaData(IntentionManagerSettings.java:78)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.a(IntentionManagerImpl.java:92)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-06-26 21:13:28,661 [  34584]  ERROR - til.concurrency.QueueProcessor - AppCode 2017.2 EAP  Build #OC-172.3095.17 
2017-06-26 21:13:28,661 [  34584]  ERROR - til.concurrency.QueueProcessor - JDK: 1.8.0_152-release 
2017-06-26 21:13:28,661 [  34584]  ERROR - til.concurrency.QueueProcessor - VM: OpenJDK 64-Bit Server VM 
2017-06-26 21:13:28,661 [  34584]  ERROR - til.concurrency.QueueProcessor - Vendor: JetBrains s.r.o 
2017-06-26 21:13:28,661 [  34584]  ERROR - til.concurrency.QueueProcessor - OS: Mac OS X 
2017-06-26 21:13:28,661 [  34584]  ERROR - til.concurrency.QueueProcessor - Last Action:  
```

Additionally in 2017.2 EAP the IDE internal error balloon pops up (this is enabled by default in EAP builds but it might also be because `com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData` now throws `PluginException` if documentation for an intention isn't found, a change between the 171 and 172 code branches). If you show the IDE Fatal Error dialog from the balloon then the option to disable the plugin is shown (which is overkill in this particular case since the lack of documentation doesn't prevent the intention from working correctly).

**Comment by codebrewer** [comment]
I should say that this issue prevents the intention from being disabled from the prefs - the only way to disable it would be to remove the plugin entirely.
