### ISSUE TITLE
Version Support 2021.1 EAP

### ISSUE THREAD

**Issue by houtzager** [seanhenry/MockGenerator#27]
Hello, 

I've been trying to use the mock generator on AppCode v2021.1 EAP. However, it's not working. When creating a spy the following error occurs:
```
2021-02-23 10:24:52,305 [96254536]  ERROR - llij.ide.plugins.PluginManager - 'com.jetbrains.swift.psi.SwiftThrowsClause com.jetbrains.swift.psi.SwiftFunctionDeclaration.getThrowsClause()' 
java.lang.NoSuchMethodError: 'com.jetbrains.swift.psi.SwiftThrowsClause com.jetbrains.swift.psi.SwiftFunctionDeclaration.getThrowsClause()'
	at codes.seanhenry.transformer.FunctionTransformer.visitFunctionDeclaration(FunctionTransformer.kt:37)
	at com.jetbrains.swift.psi.impl.SwiftFunctionDeclarationGenImpl.accept(SwiftFunctionDeclarationGenImpl.java:21)
	at com.jetbrains.swift.psi.impl.SwiftFunctionDeclarationGenImpl.accept(SwiftFunctionDeclarationGenImpl.java:26)
	at codes.seanhenry.transformer.FunctionTransformer$Companion.transform(FunctionTransformer.kt:16)
	at codes.seanhenry.transformer.ClassTransformer.visitClassDeclaration(ClassTransformer.kt:28)
	at com.jetbrains.swift.psi.impl.SwiftClassDeclarationGenImpl.accept(SwiftClassDeclarationGenImpl.java:21)
	at com.jetbrains.swift.psi.impl.SwiftClassDeclarationGenImpl.accept(SwiftClassDeclarationGenImpl.java:26)
	at codes.seanhenry.transformer.ClassTransformer$Companion.transform(ClassTransformer.kt:14)
	at codes.seanhenry.intentions.BaseGeneratingIntention.transformSuperclass(BaseGeneratingIntention.java:141)
	at codes.seanhenry.intentions.BaseGeneratingIntention.transformMockClass(BaseGeneratingIntention.java:135)
	at codes.seanhenry.intentions.BaseGeneratingIntention.invoke(BaseGeneratingIntention.java:86)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.invoke(PsiElementBaseIntentionAction.java:41)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.invoke(IntentionActionWrapper.java:66)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.lambda$invoke$0(IntentionActionWithTextCaching.java:209)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:209)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$4(ShowIntentionActionsHandler.java:251)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:105)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:948)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:104)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:251)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:227)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:215)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:226)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$3(IntentionListStep.java:135)
	at com.intellij.ide.IdeEventQueue.onFocusEvent(IdeEventQueue.java:568)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:485)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:782)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-02-23 10:24:52,306 [96254537]  ERROR - llij.ide.plugins.PluginManager - AppCode 2021.1 EAP  Build #OC-211.5787.4 
2021-02-23 10:24:52,306 [96254537]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.10; VM: Dynamic Code Evolution 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-02-23 10:24:52,306 [96254537]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2021-02-23 10:24:52,306 [96254537]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Swift Mock Generator for AppCode version: 17 
2021-02-23 10:24:52,306 [96254537]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowIntentionActions 
```

I noticed I'm running on v17 of the mock generator. When installing v18 manually, I get the message that this version is incompatible.

> Plugin 'Swift Mock Generator for AppCode' (version '18') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is OC-211.5787.4 

Thanks in advance, I very much appreciate the plugin. 😄 

Skip

**Comment by AlesMMichalek** [comment]
Same issue in stable release 2021.1

AppCode 2021.1
Build #OC-211.6693.150, built on April 23, 2021
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 8
Registry: max.suggested.heap.size=8192
Non-Bundled Plugins: com.appcodeplugins.swiftlint (1.13.3), codes.seanhenry.mockgenerator (17)

**Comment by alexhunsley** [comment]
Hi Sean, thanks for writing this plugin! I am getting a similar problem in AppCode 2021.1.1 with plugin v17 when trying to generate a spy:

```
java.lang.NoSuchMethodError: 'com.jetbrains.swift.psi.SwiftThrowsClause com.jetbrains.swift.psi.SwiftFunctionDeclaration.getThrowsClause()'
	at codes.seanhenry.transformer.FunctionTransformer.visitFunctionDeclaration(FunctionTransformer.kt:37)
	at com.jetbrains.swift.psi.impl.SwiftFunctionDeclarationGenImpl.accept(SwiftFunctionDeclarationGenImpl.java:21)
	at com.jetbrains.swift.psi.impl.SwiftFunctionDeclarationGenImpl.accept(SwiftFunctionDeclarationGenImpl.java:26)
	at codes.seanhenry.transformer.FunctionTransformer$Companion.transform(FunctionTransformer.kt:16)
	at codes.seanhenry.transformer.ProtocolTransformer.visitProtocolDeclaration(ProtocolTransformer.kt:26)
	at com.jetbrains.swift.psi.impl.SwiftProtocolDeclarationGenImpl.accept(SwiftProtocolDeclarationGenImpl.java:21)
	at com.jetbrains.swift.psi.impl.SwiftProtocolDeclarationGenImpl.accept(SwiftProtocolDeclarationGenImpl.java:26)
	at codes.seanhenry.transformer.ProtocolTransformer$Companion.transform(ProtocolTransformer.kt:13)
	at codes.seanhenry.transformer.ProtocolTransformer.visitProtocolDeclaration(ProtocolTransformer.kt:33)
	at com.jetbrains.swift.psi.impl.SwiftProtocolDeclarationGenImpl.accept(SwiftProtocolDeclarationGenImpl.java:21)
	at com.jetbrains.swift.psi.impl.SwiftProtocolDeclarationGenImpl.accept(SwiftProtocolDeclarationGenImpl.java:26)
	at codes.seanhenry.transformer.ProtocolTransformer$Companion.transform(ProtocolTransformer.kt:13)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at codes.seanhenry.intentions.BaseGeneratingIntention.transformProtocols(BaseGeneratingIntention.java:145)
	at codes.seanhenry.intentions.BaseGeneratingIntention.transformMockClass(BaseGeneratingIntention.java:132)
	at codes.seanhenry.intentions.BaseGeneratingIntention.invoke(BaseGeneratingIntention.java:86)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.invoke(PsiElementBaseIntentionAction.java:41)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.invoke(IntentionActionWrapper.java:66)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.lambda$invoke$0(IntentionActionWithTextCaching.java:209)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:209)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$4(ShowIntentionActionsHandler.java:251)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:105)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:947)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:973)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:104)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:251)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:227)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:226)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$3(IntentionListStep.java:135)
	at com.intellij.ide.IdeEventQueue.onFocusEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by johnrnyquist** [comment]
Same issue with the shipping version of 2021.1

**Comment by seanhenry** [comment]
All these issues should be fixed now. Update the plugin to v19 and use AppCode 2022.1.3.
